### ISSUE TITLE
Provide Hint in documentation how to add FX for 4 channels e.g. Powermap

### ISSUE THREAD

**Issue by christophmf** [leomccormack/SPARTA#3]
Hi,
i like to use the powermap or SLDOA from 4 channels, when i add the FX in Reaper, i can add it only to a single channel and it gives a warning on top that at least 2 or 4 channels are needed. It would be good to give a hint how to do it.

best regards
  Christoph

**Comment by leomccormack** [comment]
Hi Christoph,

Apologies my late reply, I didn't receive a notification. 
You can specify the number of channels (up to 64) using the routing options for each track. Take care to make sure the input format is ACN/SN3D (or N3D). You can get these signals (up to 7th order) by panning monophonic signals using AmbiENC, or from a spherical microphone array using Array2SH. Otherwise, there is also the AmbiX converter that let's to switch between different formats, if you have some external recordings that do not match the format options available in the plug-ins.

I hope this helps : )

Cheers,
Leo
