### ISSUE TITLE
sparta_binauraliser crashes upon reading sofa file

### ISSUE THREAD

**Issue by ReasonableHippo** [leomccormack/SPARTA#39]
The binauralizer plugin crashes once I try to read any SOFA file from the sofa website (https://www.sofaconventions.org/mediawiki/index.php/Files)

Steps to reproduce:
- Open Reaper
- Add a wave file track
- add binauralizer 
- press browse for sofa file
- select file

**Comment by leomccormack** [comment]
Hi,

Can you please let us know your OS and Reaper versions? 
Is there any crash log/information? (e.g. on MacOS, there will be an option to "see more info" when the window pops up that says REAPER had to close because of an issue. Copy and pasting that information is very helpful in narrowing the problem down).
Are you using the pre-built plugins? (in which case which version?), or have you built them yourself from source? (in which case, what commit/branch are you using?)

**Comment by ReasonableHippo** [comment]
I'm using Win10 19042.1110 with Reaper 6.32 (2e51fc) and downloaded the prebuild 2021_04_22_v1.5.0 plugins

Unfortunately, I do not get any crash information

**Comment by leomccormack** [comment]
hmm, I've tried a 2 windows PC's and a number sofa files. I cannot reproduce the crash, and without any crash logs, there's not really a clear way forward. Things to try:
Does rolling back Reaper and/or SPARTA a version or two remove the issue? 
Does the SOFA loader in e.g. compass_binaural.vst, and sparta_ambiBIN work OK? 
Did the binauraliser SOFA reader work for you previously, with this being a recent problem?

**Comment by ReasonableHippo** [comment]
The sofa reader in the compass_binaural works. I managed to get it runnning with an older version of the plugins (Win64_SPARTA_2020_12_22_v1.4.4).

Thanks

**Comment by leomccormack** [comment]
The SOFA reader is slightly different for compass_binaural than the other SPARTA plugins. I don't yet know what could have changed to the binauraliser between v1.4.4 and v1.5.0. But these 2 things at least help to narrow things down. I'll try to see what could have happened here. 

Thank you for letting me know! : )
