### ISSUE TITLE
Binauralizer interpolation mode for maximum accuracy

### ISSUE THREAD

**Issue by a-zhendi** [leomccormack/SPARTA#43]
Hello.
I am trying to use sparta binauralizer with my custom HRTF sofa to monitor multi-channel audio.
Which interpolation mode ("Triangular" or "Triangular PS") is most accurate? 
Given the input 5.1 source I am currently working with, these interpolation options   produce very obvious difference in binauralized output.
I don't know which mode should I trust more.
I am not expert but I guess that "Triangular PS" is less accurate because of some simplification of processing algorythm.
So can someone clarify it for me plz?
Also why we need two modes instead of just one mode with maximum accuracy?

**Comment by a-zhendi** [comment]
After some comparison of the binaural monitoring with monitoring in real multi-channel environment I can confirm that with the 'Triangular' the plugin (with my personal hrtf) sounds much more comparable to real space.

**Comment by a-zhendi** [comment]
However, a few questions still actual for me:
1) Reasons why the "Triangular PS" mode exist?
2) Can developers add "None" option for interpolation? So the closest point will be used from the hrtf model to specified azimuth and elevation values? The goal of this option to get the most accurate binauralization.

**Comment by leomccormack** [comment]
Hi! 

The "Triangular" mode directly applies interpolation weights to the complex HRTF spectra, and sums them up to obtain an interpolated HRTF, which is then convolved with the input signal in the frequency domain. This will likely be the most "accurate" in terms of localisation. Although, note that the true HRTF for a direction between other HRTFs is technically undefined. We're just imposing a "model" saying that triangular interpolation [using amplitude normalised VBAP gains in this case] should produce a reasonable interpolated HRTF. 

The "Triangular PS" mode then implements the approach described in [this paper](https://www.researchgate.net/profile/Symeon-Delikaris-Manias/publication/284735029_Parametric_binaural_rendering_utilizing_compact_microphone_arrays/links/5a2023e8458515341c8392dc/Parametric-binaural-rendering-utilizing-compact-microphone-arrays.pdf). It applies the interpolation weights to the HRTF magnitude responses and inter-aural/channel time differences separately, before recombining them to obtain the interpolated HRTF. The localisation should be substantially the same as the "Triangular" mode, but adaptive time-varying directions (especially over frequency, e.g. in the case of the CroPaC-Binaural and COMPASS plugins) will benefit from this phase simplification.  However, this localisation similarity is then contingent on the ITD estimation being correct, which may indeed deviate slightly in practice...

However! You're right. I'm assuming that most people will use the plugin for static binauralisations, so to mitigate any issues arising due to the PS variant, "Triangular" should probably be the default mode. I'll change this. Thank you! : )

**Comment by leomccormack** [comment]
Ah yes. A "use Nearest HRTF" option is also a possibility. It's on the list : )
