### ISSUE TITLE
Sparta AmbiRoomSim: no of sources > 10 , only shows as 1s

### ISSUE THREAD

**Issue by Andertve** [leomccormack/SPARTA#48]
Issue in title.
This is in Reaper 6.42, Mac OS X 11.6 running on a M1 MacBook.
Attached is a screenshot of 12 sources.
Seems like it does not shows 2-digit numbers.

<img width="792" alt="Skjermbilde 2021-12-07 kl  20 44 19" src="https://user-images.githubusercontent.com/23010148/145096165-3de2767d-a3a1-40d9-8066-5f066091e034.png">

**Comment by leomccormack** [comment]
aha! Well spotted!

The culprit must be this:
https://github.com/leomccormack/SPARTA/blob/b696ecbd9c9323c47b61147e349a3f014afcf57b/audio_plugins/_SPARTA_ambiRoomSim_/src/pannerView.cpp#L132

srcIcon needs to be translated _and_ enlarged, in order to display the second digit. If you're OK with doing this yourself, then feel free submit a PR. Otherwise, I'll leave this issue open, and address it before the next release. :)

Thanks!
