### ISSUE TITLE
Does the COMPASS upmixer have a denormals issue? 

### ISSUE THREAD

**Issue by muziker** [leomccormack/SPARTA#53]
I had this enabled to convert a first order ambisonic to 5th order, but as soon as the audio stops playing the cpu starts spiking heavily. This is probably a denormals issue, and once i disabled the plugin during a spike, the cpu load went back to normal. Are the plugins compiled with DAZ and FTZ ? 

Tested with reaper 6.45 linux and Linux_SPARTA_2021_11_22_v1.5.2.

**Comment by muziker** [comment]
I've added a noise generator plugin in the chain and the cpu usage doesn't spike any longer.

**Comment by leomccormack** [comment]
Hi, apologies for the delay! I can't reproduce any high cpu usage when idle/silent-input. However, since strict IEEE 754 standard conformance isn't necessary, the compiler `-ffast-math` flag will now be used for the forthcoming v1.6.0 release and future releases, which may address the problem. 

However, if the problem persists, please re-open the issue : )
