### ISSUE TITLE
Binauralizer is silent

### ISSUE THREAD

**Issue by SDX-LV** [leomccormack/SPARTA#62]
Hi.

Thank you for the latest release with a fix for crashes on loading of certain SOFA files.

I have now tested latest Binauralizer on 2 different Windows computers with 2 different hosts and must conclude that: **every time I load a custom HRIR SOFA file there is no sound out of Binauralizer**. These are the [same HRTFs](https://github.com/leomccormack/SPARTA/files/8669881/HRIR_ARI_48000.zip) which previously tended to crash the VST. Now they load nicely, I can see that HRIR is loaded, only no sound comes out.  The default HRTF still works, only the custom SOFA HRIR is silent.

Also minor thing:  the version number on the plugin says "Build Data April 3 2022" which is most likely wrong. 

Best regards,
Sergejs

**Comment by SDX-LV** [comment]
A short test showed that AmbiBin does work with the custom HRTF. 
But Binauraliser goes silent with custom HRTFs on all hosts that I tried.

**Comment by leomccormack** [comment]
Hey, I identified the issue being related to the diffuse-field equalisation (since disabling this fixed the silence problem). 

I then narrowed the problem down to the calculation of the grid integration weights, which had some numerical stability issues which I suspect is down to the very irregular grid in the HRIR dataset you shared:

<img width="941" alt="Screenshot 2022-06-20 at 11 35 58" src="https://user-images.githubusercontent.com/36531075/174607447-a9651fed-54aa-4a61-bda1-b08d84f5923e.png">

For reference, the default HRIR set is:

<img width="938" alt="Screenshot 2022-06-20 at 11 36 12" src="https://user-images.githubusercontent.com/36531075/174607603-06983f96-2969-46d6-8927-4f1ff5a7d4bf.png">

I've now circumvented the issue by removing the grid weights in the diffuse-field EQ code for larger grids, which I had done in the past for the ambiBIN plugin. However, this is not a perfect solution, but it will work to improve the stability of this part of the code for now. Although I would recommend using a more uniform HRIR measurement/simulation grid, or applying any diffuse-field equalisation yourself to the HRIRs and disabling this option in the plugin for optimal results. 

Many thanks! : )
Leo

**Comment by SDX-LV** [comment]
Thank you!
It now works as you described it! :)  

I believe this specific sampling grid is the same as used in https://www.oeaw.ac.at/isf/das-institut/software/hrtf-database . In practice Mesh2HRTF can simulate any sampling grid (even multiple in the same simulation) with minimal performance impact, so if there is some optimal grid that you would suggest, it can be directly implemented. 

For example with Mesh2HRTF it would be possible to define a very high resolution sampling grid and then "[use Nearest HRTF](https://github.com/leomccormack/SPARTA/issues/43)" option with/without Diffuse field EQ.

I now have a working setup to use virtual 7.1 surround sound over SPARTA Binauraliser with [Mesh2HRTF individual HRTF](https://youtu.be/ccw8SMG_kqw) and head-tracking for system-wide sound reproduction on Windows.

I will still work on better headphone EQ, maybe the latencies can be reduced; adding extra effects and in general more testing is needed, but this is probably the most advanced virtual surround setup possible in 2022. I will need to make a tutorial for this at the end of the summer.

![Voicemeeter Banana Insert ASIO config p2](https://user-images.githubusercontent.com/17532214/174680476-a089fe7a-a018-4966-9881-fb548971eedf.png)

Thank you,
Sergejs
